module "project-factory" {
  source                    = "terraform-google-modules/project-factory/google"
  version                   = "15.0.1"
  activate_apis             = var.activate_apis
  auto_create_network       = var.auto_create_network
  billing_account           = var.billing_account
  custom_roles              = var.custom_roles
  editors                   = var.editors
  extra_bindings_members    = var.extra_bindings_members
  extra_bindings_roles      = var.extra_bindings_roles
  gce_service_account_roles = var.gce_service_account_roles
  labels                    = var.labels
  lien_reason               = var.lien_reason
  name                      = var.name
  oslogin                   = var.oslogin
  oslogin_admins            = var.oslogin_admins
  oslogin_users             = var.oslogin_users
  owners                    = var.owners
  parent                    = var.parent
  prefix                    = var.prefix
  viewers                   = var.viewers
}
