module "kubernetes-engine" {
  source              = "terraform-google-modules/kubernetes-engine/google"
  version             = "38.1.0"
  autoscaling         = var.autoscaling
  cluster             = var.cluster
  initial_node_count  = var.initial_node_count
  kubernetes_version  = var.kubernetes_version
  location            = var.location
  management          = var.management
  max_pods_per_node   = var.max_pods_per_node
  name                = var.name
  name_prefix         = var.name_prefix
  network_config      = var.network_config
  node_config         = var.node_config
  node_count          = var.node_count
  node_locations      = var.node_locations
  placement_policy    = var.placement_policy
  project             = var.project
  queued_provisioning = var.queued_provisioning
  timeouts            = var.timeouts
  upgrade_settings    = var.upgrade_settings
}
