variable "channel" {
  description = "The channel to use for this ASM installation."
  type        = string
  default     = ""
}

variable "cluster_location" {
  description = "The cluster location for this ASM installation."
  type        = string
  default     = ""
}

variable "cluster_name" {
  description = "The unique name to identify the cluster in ASM."
  type        = string
  default     = ""
}

variable "enable_cni" {
  description = "Determines whether to enable CNI for this ASM installation. Required to use Managed Data Plane (MDP)."
  type        = bool
  default     = false
}

variable "enable_fleet_registration" {
  description = "Determines whether the module enables the mesh feature on the fleet."
  type        = bool
  default     = false
}

variable "enable_mesh_feature" {
  description = "Determines whether the module registers the cluster to the fleet."
  type        = bool
  default     = false
}

variable "enable_vpc_sc" {
  description = "Determines whether to enable VPC-SC for this ASM installation. For more information read https://cloud.google.com/service-mesh/docs/managed/vpc-sc"
  type        = bool
  default     = false
}

variable "fleet_id" {
  description = "The fleet to use for this ASM installation."
  type        = string
  default     = ""
}

variable "multicluster_mode" {
  description = "[Preview] Determines whether remote secrets should be autogenerated across fleet cluster."
  type        = string
  default     = "manual"
}

variable "project_id" {
  description = "The project in which the resource belongs."
  type        = string
  default     = ""
}
